FROM debian:13

ENV container=docker
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
      ansible-core \
      ca-certificates \
      curl \
      dbus \
      gzip \
      libicu-dev \
      libssl-dev \
      python3 \
      python3-apt \
      sudo \
      systemd \
      systemd-sysv \
      tar \
      zlib1g \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && systemctl mask \
      dev-hugepages.mount \
      sys-fs-fuse-connections.mount \
      systemd-remount-fs.service

STOPSIGNAL SIGRTMIN+3
VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
